services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      #ME_CONFIG_BASICAUTH_USERNAME: admin
      #ME_CONFIG_BASICAUTH_PASSWORD: admin
      MONGO_INITDB_DATABASE: app
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-server
    restart: always
    depends_on:
      - mongo
    environment:
      ENV: local
      MONGO_CONNECTION_URI: mongodb://root:root@mongo:27017/?authSource=admin
      MONGO_DATABASE_NAME: "app"
    ports:
      - "8080:8080"
    #healthcheck:
    #  test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 20s

volumes:
  mongo_data:
